# To create a github access token - Go to Profile > Settings > Developer Settings > Github Access Tokens
name: Release

on:
  workflow_dispatch:
    branches: [add-releaser]
    inputs:
      tag:
        description: "New Build Tag"
        required: true
#      commit_message:
#        description: "Commit Message"
#        required: true


jobs:
  tag:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ github.sha }}
        fetch-depth: '0'

    - name: Print Input
      run: echo "${{ inputs.tag }}"

    - name: Bump version and push tag
      uses: anothrNick/github-tag-action@1.55.0
      env:
        GITHUB_TOKEN: ${{ secrets.REPO_TOKEN }}
        WITH_V: true
        CUSTOM_TAG: "v${{ inputs.tag }}"

#  docker:
#    needs: tag
#    runs-on: ubuntu-latest
#    steps:
#      - name: Add SHORT_SHA env property with commit short sha
#        run: echo "SHORT_SHA=`echo ${GITHUB_SHA} | cut -c1-8`" >> $GITHUB_ENV
#      - name: Set up QEMU
#        uses: docker/setup-qemu-action@v2
#      - name: Set up Docker Buildx
#        uses: docker/setup-buildx-action@v2
#      - name: Login to DockerHub
#        uses: docker/login-action@v2
#        with:
#          username: ${{ secrets.DOCKERHUB_USERNAME }}
#          password: ${{ secrets.DOCKERHUB_TOKEN }}
#
#      - name: Build and push
#        uses: docker/build-push-action@v3
#        with:
#          push: true
#          platforms: linux/amd64,linux/arm/v7
#          tags: admiralpiett/musizticle:${{env.SHORT_SHA}},admiralpiett/musizticle:latest
